# Generated by Django 3.1 on 2020-09-08 08:56

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('source', models.ImageField(upload_to='attachments', verbose_name='source')),
                ('size', models.IntegerField(default=0, help_text='单位byte', verbose_name='image size')),
                ('width', models.SmallIntegerField(default=0, help_text='单位px', verbose_name='image width')),
                ('height', models.SmallIntegerField(default=0, help_text='单位px', verbose_name='image height')),
                ('ftype', models.CharField(blank=True, max_length=50, null=True, verbose_name='image type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='image desc')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachment',
                'ordering': ['-created'],
            },
        ),
    ]
