# Generated by Django 3.0.1 on 2020-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='source',
            field=models.ImageField(default='', upload_to='uploads/attachments/%Y%m'),
            preserve_default=False,
        ),
    ]
