# Generated by Django 3.0.1 on 2020-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20200224_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ftype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
