# Generated by Django 3.0.1 on 2020-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20200224_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='height',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='width',
            field=models.SmallIntegerField(default=0),
        ),
    ]
