# Generated by Django 2.2.7 on 2020-03-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_auto_20200224_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created'], 'verbose_name': 'attachment', 'verbose_name_plural': 'attachment'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='image desc'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ftype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='image type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='height',
            field=models.SmallIntegerField(default=0, help_text='单位px', verbose_name='image height'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.IntegerField(default=0, help_text='单位byte', verbose_name='image size'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source',
            field=models.ImageField(upload_to='uploads/attachments/%Y%m', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='width',
            field=models.SmallIntegerField(default=0, help_text='单位px', verbose_name='image width'),
        ),
    ]
