# Generated by Django 3.0.4 on 2020-05-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_attachment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
