# Generated by Django 3.0.5 on 2020-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_attachment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='source',
            field=models.ImageField(upload_to='attachments', verbose_name='source'),
        ),
    ]
