# Generated by Django 3.0.5 on 2020-05-08 09:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('attachments', '0007_auto_20200508_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
